controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

tricycle_steering_controller:
  ros__parameters:
    wheelbase: 0.171
    wheel_track: 0.168
    front_wheels_radius: 0.0368
    rear_wheels_radius: 0.0368
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_wheels_names: ["virtual_front_wheel_joint"]
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    # twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    # pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: true
    use_stamped_vel: false
