<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="inertial_macros.xacro" />

  <xacro:macro name="carlikebot" params="prefix">

    <!-- VARIABLES-->
    <xacro:property name="chassis_length" value="0.27" />
    <xacro:property name="chassis_width" value="0.1205" />
    <xacro:property name="chassis_height" value="0.115" />
    <xacro:property name="chassis_to_back_wheels_distance" value="0.048" />
    <xacro:property name="chassis_mass" value="1.1" />
    <xacro:property name="wheel_track" value="0.168" />
    <xacro:property name="wheel_radius" value="0.0368" />
    <xacro:property name="wheel_length" value="0.0295" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_base" value="0.171" />

    <!-- BASE LINK -->
    <link name="base_link" />

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link" />
      <child link="base_footprint" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint" />

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
      <parent link="base_link" />
      <child link="chassis" />
      <origin xyz="-${chassis_to_back_wheels_distance} 0.0 0.0" />
    </joint>
    <link name="chassis">
      <visual>
        <origin xyz="${chassis_length/2} 0.0 ${chassis_height/3}" />
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="${chassis_length/2} 0.0 ${chassis_height/3}" />
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
        </geometry>
      </collision>
      <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}"
        z="${chassis_height}">
        <origin xyz="0.0 0 0.0" />
      </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
      <material>Gazebo/White</material>
    </gazebo>

    <!-- REAR LEFT WHEEL LINK -->
    <joint name="rear_left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="rear_left_wheel" />
      <origin xyz="0 ${wheel_track/2} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="rear_left_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}"
        radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_left_wheel">
      <material>Gazebo/Blue</material>
    </gazebo>

    <!-- REAR RIGHT WHEEL LINK -->
    <joint name="rear_right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="rear_right_wheel" />
      <origin xyz="0 -${wheel_track/2} 0" rpy="${pi/2} 0 0" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="rear_right_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}"
        radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_right_wheel">
      <material>Gazebo/Blue</material>
    </gazebo>

    <!-- VIRTUAL FRONT WHEEL LINK-->
    <joint name="virtual_front_wheel_joint" type="revolute">
      <parent link="base_link" />
      <child link="virtual_front_wheel" />
      <origin xyz="${wheel_base} 0.0 0.0" rpy="0 0 ${pi/2}" />
      <axis xyz="0 0 1" />
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0" />
      <dynamics damping="0.2" />
    </joint>

    <link name="virtual_front_wheel">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="black" />
      </visual>
    </link>


    <!-- FRONT RIGHT WHEEL LINK-->
    <joint name="front_right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="front_right_wheel" />
      <origin xyz="${wheel_base} -${wheel_track/2} 0" rpy="0 0 ${pi/2}" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.2" />
      <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>

    <link name="front_right_wheel">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}"
        radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <!-- FRONT LEFT WHEEL LINK-->
    <joint name="front_left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="front_left_wheel" />
      <origin xyz="${wheel_base} ${wheel_track/2} 0" rpy="0 0 ${pi/2}" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.2" />
      <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>

    <link name="front_left_wheel">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}"
        radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

  </xacro:macro>

  <!-- CASTER WHEEL LINK-->
  <!-- <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel" />
        <origin xyz="0.24 0.0 0.0" />
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.02" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.02" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.02">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo> -->
</robot>